### ISSUE TITLE
EFSBackup runs into timeout when mounting EFS volumes

### ISSUE THREAD

**Issue by peteroruba** [aws-samples/data-pipeline-samples#59]
Hello

I am facing a timeout issue when applying the DataPipeline template for EFS Backups. Usually that effect suggests a wrong security group configuration, however, I manually launched an EC2 instance belonging to mySrcSecGroupID and myBackupSecGroupID and accessing both EFS volumes was OK.

Attaching the StdErr.log below.
Thanks,
Peter

--2016-09-22 08:52:24--  https://s3-us-west-2.amazonaws.com/XXXXXX/efs-backup.sh
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.169.16
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.169.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2986 (2.9K) [application/x-sh]
Saving to: â€˜efs-backup.shâ€™

```
 0K ..                                                    100% 93.5M=0s
```

2016-09-22 08:52:24 (93.5 MB/s) - â€˜efs-backup.shâ€™ saved [2986/2986]

mount.nfs: Connection timed out
mount.nfs: Connection timed out
rm: cannot remove â€˜/tmp/efs-backup.logâ€™: No such file or directory

**Comment by awsdan** [comment]
Thanks for your comment! Sorry to hear about the connection troubles. I'll take a look and let you know what I find.

-Dan

**Comment by peteroruba** [comment]
Thanks, that issue actually has resolved. Looks like I needed to give it a few hours after creating the EFS mount points before running it.

-Peter

**Comment by awsdan** [comment]
Oh, awesome. Thanks for letting me know!
