### ISSUE TITLE
RedshiftPassword variable is prefixed with an asterix 

### ISSUE THREAD

**Issue by busybee1149** [aws-samples/data-pipeline-samples#66]
"username": "#{myRedshiftUsername}",
      "*password": "#{*myRedshiftPassword}"
{
      "description": "The password for the above user to establish connection to the Redshift cluster.",
      "id": "*myRedshiftPassword",
      "type": "String"
    }

**Comment by pushpeshg** [comment]
@busybee1149 : The asterix is a special character in AWS  Datapipeline which specifies an encrypted field (such as passwords). It indicates that the Datapipeline service should encrypt the contents of the field in transit.

Have a look at this:
http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-pipeline-characters.html
